export default {
  common: {
    SERVER_ERROR: 'SERVER_ERROR'
  },

  auth: {
    INVALID_API_KEY: 'INVALID_API_KEY',
    INVALID_AUTH_TYPE: 'INVALID_AUTH_TYPE',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    PERMISSION_DENIED: 'PERMISSION_DENIED'
  },

  loginToken: {
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_DISABLED: 'TOKEN_DISABLED',
  },

  user: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_DISABLED: 'USER_DISABLED',
    USERNAME_PASSWORD_NOT_DEFINED: 'USERNAME_PASSWORD_NOT_DEFINED',
    USERNAME_DUPLICATED: 'USERNAME_DUPLICATED'
  },

  register: {
    INFO_EMPTY: 'INFO_EMPTY'
  }
}